### ISSUE TITLE
테스트를 작성하는데 드는 공수(Cost)보다 테스트를 작성해서 득(Benefit)을보는 지점은 언제부터일까?

### ISSUE THREAD

**Issue by minje0204** [heejjinkim/unit-testing-study#3]
### 관련 책 내용
[p.130]
- 테스트가 얼마나 이해하기 어려운가?
  - 테스트 코드를 `일급 시민`으로 취급하라.
      -> 애플리케이션 코드와 동일하게 취급하란 이야기
> `일급 시민`이란?
> 컴퓨터 과학에서 "일급 시민(First-class citizen)"이라는 개념은 특정한 요소가 다른 요소와 **`동일한 권리`**와 특성을 가지고 있다는 것을 의미합니다.

### **내 생각**  
테스트 코드를 일급 시민으로 대하면, 더더욱 테스트 코드를 작성하고 유지보수하는 공수가 들어가는데 
![image](https://github.com/user-attachments/assets/db959a6c-b2f2-4e58-8af7-055a5f5a6146)
Benefit > Cost이 되는 지점(점선과 실선이 교차되는)이 내가 생각했던 것보다 더 우측으로 갈 것 같다.

개발하고 있는 프로젝트가 얼마나 진척(복잡해)될지를 개발하는 시점에 예상할수는 없는데, 너무 이상적인 얘기가 아닌가?

### **찾아볼 것**
"좋은 테스트코드를 위해 얼마나 공수를 들일지?"
정답은 없고 프로젝트와 개발자의 경험치에 따라 달라질까? 그렇다면 경험자들은 어떤 기준으로 판단할까

**Comment by eun-seong** [comment]
> 개발하고 있는 프로젝트가 얼마나 진척(복잡해)될지를 개발하는 시점에 예상할수는 없는데, 너무 이상적인 얘기가 아닌가?

그래서 초반에 테스트코드를 작성하는 쪽이 굉장히 많은 리소스가 소요된다는 것을 나타내는 그래프인 것 같습니다.
고려해야 할 것이 많고 확실하게 측정할 수 없어서 그래프가 그렇게 나타나는 게 아닐까 싶습니다.
그리고 프로젝트가 진행되면서 계속해서 복잡해진다면, 테스트코드가 있는 것이 점점 유지보수 비용이 줄어드는 것이고요!
저도 직접 경험해보지 못해서 이미 알고 계신 내용을 반복해서 말씀드린 것 같긴하지만요🥲

테스트 코드나 코드 품질을 높게 유지하려고 하는 팀이나 회사에서, 개발자들이 뭐하고 있나 돌아보면 70%는 테스트코드를 작성하고 있다는 영상을 본 적이 있어요. 테스트 코드 작성에 익숙해지면 실제 비즈니스 코드 작성하는 것은 그에 비해 금방 완료된다고도 주변에서 들은 적이 있구요.
팀 내 문화가 굉장히 중요하겠지만, 테스트 코드가 중요한 가치로 자리잡고 있는 팀은 시간을 많이 소요하더라고요!

그래도 테스트코드 작성하느라 시간을 한도끝도 없이 사용하는 것도 비현실적이라, 실제로 실무자들이 어떤 기준으로 테스트 코드 작성에 어느 정도까지 시간을 소요하는지는 궁금하네요🤔
